version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  spring-app:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: devops_project
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - internal

volumes:
  mysql-data:

networks:
 internal :

