version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  spring-app:
    container_name: DevOps_Project
    image: firas97/devops_project
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root"
      }'
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - internal

volumes:
  mysql-data:

networks:
 internal :



